### PR TITLE
Update instructions and docker compose to include local mongodb

### PR DESCRIPTION
**Pull request by sthapa**
Tested instructions and it looks like everything works, I've updated the instructions and config to let users quickly setup a local mongodb instance for dev use. It's commented out by default but can easily be re-enabled.

### CODE REVIEW

**Review by felimartina — APPROVED** [review]
lgtm

**Review by felimartina — COMMENTED** [review]
@sthapa , I believe this same docker-compose.yml file is being used by the servers to launch the API and that is why we don't have the DB container on it.
I guess we could have a cocker-compose.dev.yml with all it needs for local development.

What do you think?

**Comment by sthapa** [comment]
I've left the db image commented out in the docker compose file.  Is it uncommented and used on the server?  If so, creating an alternate file for dev is the way to go.

**Review by felimartina — COMMENTED** [review]
Well, yes. It is commented in the servers as well. Not for any particular reason, though.
I still think it would be nice to have a prod and a local/dev version of the docker compose.

On a different note, what do you think about having our DB as a docker image in prod. My reasoning is that at the end of the day our DB is static and read-only. We can create a new version of the db (docker image) everytime we re-import/update the DB. This will let us avoid having our DB hosted on a third party service (such as mlab). Of course, it will not be suitable to let ACLU manually edit features.

IDK, just a thought! let me hear yours.

**Comment by sthapa** [comment]
I guess I'm not sure why the db image part matters since the old one was a dummy and is commented out in both cases so it shouldn't affect the prod server.  Also, I think there's an argument to be made for having a single file with the dev and prod configs so that differences don't creep in and cause issues when going from dev to prod.

About having the DB as a docker image in prod, I'm somewhat neutral on that.  I think a pro is being able to gain some independence from mlab and being able to control the mongo version.  The con is having an additional layer of stuff and a slight performance hit.  If we use a persistent volume, it'd work for the aclu since they can manually edit features and have it saved on the persistent store.

**Comment by felimartina** [comment]
Yes, there is no problem with having the db image commented it out since we have the explanation in the README.md file. My argument about having a docker-compose.dev.yml file is that so people dont have to uncomment something to run it locally (mainly because that often leads to PRs and commits that roll back changes to the file or we might end up approving a PR with that part uncommented)
Just a thought thou...

let's go ahead and get this PR merge then we can discuss further, not a big deal tbh

**Pull request merged**
